language: sh

os:
    - linux
    - windows
    - osx

osx_image:
    - xcode11.2
    
addons:
  apt:
    packages:
    - gcc
    - cmake
    - libglew-dev
    - libx11-dev
    - libxrandr-dev
    - libxi-dev
    - libasound2-dev
    - libc6-dev

before_script:
  - mkdir build
  - cd build

script: 
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then cmake .. -DCMAKE_BUILD_TYPE=Release; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PATH=$PATH:/c/Program\ Files/CMake/bin; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake .. -G "Visual Studio 15 2017 Win64"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake --build . --config Release --target ALL_BUILD -- -verbosity:m; fi
  - if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then cmake .. -DCMAKE_BUILD_TYPE=Release; fi

branches:
  only:
    - master

notifications:
  email: false